services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/public:/var/www/html/public
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html
