services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html

        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=personal_page
            - MYSQL_USER=user
            - MYSQL_PASSWORD=secret
            - MYSQL_PORT=3306
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306" #default MySQL port
        restart: unless-stopped #change to always for deployment
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: personal_page
            MYSQL_USER: user
            MYSQL_PASSWORD: password

volumes:
    mysqldata: